# Generated by Django 4.2.7 on 2025-12-01 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField(help_text='Age in years')),
                ('identification_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like color, markings, etc.')),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('under_treatment', 'Under Treatment')], default='healthy', max_length=20)),
                ('is_archived', models.BooleanField(default=False, help_text='Soft delete flag - archived cattle are not permanently deleted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cattle',
                'verbose_name_plural': 'Cattle',
                'db_table': 'cattle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CattleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cattle.cattle')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cattle History',
                'verbose_name_plural': 'Cattle Histories',
                'db_table': 'cattle_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['cattle', '-changed_at'], name='cattle_hist_cattle__b97068_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['owner', 'is_archived'], name='cattle_owner_i_921631_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['identification_number'], name='cattle_identif_6cfaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='cattle',
            index=models.Index(fields=['health_status'], name='cattle_health__e64dc5_idx'),
        ),
    ]
