# Generated by Django 4.2.7 on 2026-01-09 17:43

import cattle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional cattle image (JPEG, PNG, WebP, max 5MB)', null=True, upload_to=cattle.models.cattle_image_upload_path, validators=[cattle.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='identification_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cattle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('owner', 'identification_number'), name='unique_identification_per_owner'),
        ),
    ]
