# Generated by Django 4.2.7 on 2025-12-26 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('disease_alert', 'Disease Alert'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_update', 'Consultation Update'), ('treatment_reminder', 'Treatment Reminder'), ('vaccination_reminder', 'Vaccination Reminder'), ('emergency_alert', 'Emergency Alert'), ('outbreak_warning', 'Outbreak Warning'), ('system_message', 'System Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cattle.cattle')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.consultation')),
                ('disease_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.diseasealert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('disease_alert', 'Disease Alert'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_update', 'Consultation Update'), ('treatment_reminder', 'Treatment Reminder'), ('vaccination_reminder', 'Vaccination Reminder'), ('emergency_alert', 'Emergency Alert'), ('outbreak_warning', 'Outbreak Warning'), ('system_message', 'System Message')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('default_send_email', models.BooleanField(default=False)),
                ('default_send_sms', models.BooleanField(default=False)),
                ('default_send_push', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_alerts_enabled', models.BooleanField(default=True)),
                ('disease_alerts_email', models.BooleanField(default=True)),
                ('disease_alerts_sms', models.BooleanField(default=False)),
                ('disease_alerts_push', models.BooleanField(default=True)),
                ('consultation_reminders', models.BooleanField(default=True)),
                ('consultation_updates', models.BooleanField(default=True)),
                ('consultation_messages', models.BooleanField(default=True)),
                ('health_reports', models.BooleanField(default=True)),
                ('treatment_reminders', models.BooleanField(default=True)),
                ('vaccination_reminders', models.BooleanField(default=True)),
                ('emergency_alerts', models.BooleanField(default=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('regional_disease_alerts', models.BooleanField(default=True)),
                ('new_consultation_requests', models.BooleanField(default=True)),
                ('outbreak_warnings', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('recipient', models.CharField(max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_48663d_idx'), models.Index(fields=['channel', 'status'], name='notificatio_channel_169003_idx')],
                'unique_together': {('notification', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'priority'], name='notificatio_status_c0e5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
    ]
