# Generated by Django 4.2.7 on 2025-12-26 17:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_protocolstep_treatment_treatmentcategory_and_more'),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('chat', 'Chat'), ('voice', 'Voice Call'), ('video', 'Video Call')], max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('case_description', models.TextField()),
                ('symptoms_reported', models.TextField(blank=True)),
                ('ai_predictions', models.JSONField(default=list, help_text='AI disease predictions that triggered this consultation')),
                ('disease_location', models.JSONField(default=dict, help_text='Location where disease was detected')),
                ('veterinarian_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('owner_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='cattle.cattle')),
                ('cattle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_owner', to=settings.AUTH_USER_MODEL)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultations',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('ai_detection', 'AI Disease Detection'), ('symptom_report', 'Symptom Report'), ('outbreak_warning', 'Outbreak Warning')], max_length=20)),
                ('disease_name', models.CharField(max_length=200)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('location', models.JSONField(help_text='Location where disease was detected')),
                ('affected_radius_km', models.IntegerField(default=10)),
                ('ai_prediction_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_alerts', to='cattle.cattle')),
            ],
            options={
                'db_table': 'disease_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinarianNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('acknowledged', 'Acknowledged')], default='sent', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from vet to disease location', max_digits=10)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('disease_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.diseasealert')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='notified_veterinarians',
            field=models.ManyToManyField(related_name='received_disease_alerts', through='consultations.VeterinarianNotification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='symptom_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.symptomentry'),
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File'), ('system', 'System Message')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='consultation_images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='consultation_files/')),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinarianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('vet_type', models.CharField(choices=[('government', 'Government Veterinarian'), ('private', 'Private Veterinarian')], max_length=20)),
                ('specializations', models.JSONField(default=list, help_text='List of specialization areas')),
                ('years_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('service_radius_km', models.IntegerField(default=50, help_text='Service radius in kilometers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('is_available', models.BooleanField(default=True)),
                ('is_emergency_available', models.BooleanField(default=False)),
                ('working_hours', models.JSONField(default=dict, help_text='Working hours for each day of the week')),
                ('consultation_fee_chat', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('consultation_fee_voice', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('consultation_fee_video', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('emergency_fee_multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Multiplier for emergency consultations', max_digits=3)),
                ('qualification', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='vet_profiles/')),
                ('total_consultations', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_profiles',
                'ordering': ['-average_rating', '-total_consultations'],
                'indexes': [models.Index(fields=['city', 'state'], name='veterinaria_city_1d6096_idx'), models.Index(fields=['latitude', 'longitude'], name='veterinaria_latitud_45312d_idx'), models.Index(fields=['is_available', 'is_verified'], name='veterinaria_is_avai_e9339e_idx'), models.Index(fields=['vet_type'], name='veterinaria_vet_typ_c8deec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='veterinariannotification',
            index=models.Index(fields=['veterinarian', 'status'], name='veterinaria_veterin_0df579_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinariannotification',
            index=models.Index(fields=['disease_alert'], name='veterinaria_disease_148c64_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='veterinariannotification',
            unique_together={('veterinarian', 'disease_alert')},
        ),
        migrations.AddIndex(
            model_name='diseasealert',
            index=models.Index(fields=['status', '-created_at'], name='disease_ale_status_853682_idx'),
        ),
        migrations.AddIndex(
            model_name='diseasealert',
            index=models.Index(fields=['disease_name'], name='disease_ale_disease_40a2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationmessage',
            index=models.Index(fields=['consultation', 'sent_at'], name='consultatio_consult_af450c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['cattle_owner', '-scheduled_time'], name='consultatio_cattle__ae902c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['veterinarian', '-scheduled_time'], name='consultatio_veterin_e140e2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status', 'priority'], name='consultatio_status_736176_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['scheduled_time'], name='consultatio_schedul_e80931_idx'),
        ),
    ]
