# Generated by Django 4.2.7 on 2026-01-09 19:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_add_image_and_owner_scoped_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_protocolstep_treatment_treatmentcategory_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_veterinarians', models.JSONField(default=list, help_text='List of veterinarian IDs who were notified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When this request expires if not accepted')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_by', models.JSONField(default=list, help_text='List of veterinarian IDs who declined this request')),
                ('assigned_veterinarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='cattle.cattle')),
                ('cattle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinarianPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('treatment_plan', models.TextField(blank=True)),
                ('last_consultation', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinarian_patients', to='cattle.cattle')),
                ('cattle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle_under_vet_care', to=settings.AUTH_USER_MODEL)),
                ('consultation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_records', to='consultations.consultationrequest')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_patients',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinarianNotificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_channels', models.JSONField(default=list, help_text='List of channels used for notification')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('responded', 'Responded')], default='sent', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from veterinarian to cattle location', max_digits=10)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.consultationrequest')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_notification_requests',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='VeterinarianDashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('pending_requests', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('active_patients', models.IntegerField(default=0)),
                ('emergency_responses', models.IntegerField(default=0)),
                ('average_response_time', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average response time in minutes', max_digits=10)),
                ('patient_satisfaction_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('consultation_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('emergency_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('veterinarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(help_text='Detailed description of observable symptoms')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('ai_predictions', models.JSONField(default=list, help_text='AI disease predictions for this symptom report')),
                ('location', models.JSONField(default=dict, help_text='Location coordinates and address where symptoms were observed')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('notified', 'Veterinarians Notified'), ('accepted', 'Accepted by Veterinarian'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='cattle.cattle')),
                ('cattle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to=settings.AUTH_USER_MODEL)),
                ('symptom_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='health.symptomentry')),
            ],
            options={
                'db_table': 'symptom_reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('treatment', 'Treatment'), ('follow_up', 'Follow-up'), ('general', 'General')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Whether this note is private to the veterinarian')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='consultations.veterinarianpatient')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('follow_up_type', models.CharField(choices=[('check_up', 'Check-up'), ('treatment_review', 'Treatment Review'), ('medication_check', 'Medication Check'), ('recovery_assessment', 'Recovery Assessment')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_schedules', to='consultations.veterinarianpatient')),
            ],
            options={
                'db_table': 'follow_up_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='symptom_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='consultations.symptomreport'),
        ),
        migrations.CreateModel(
            name='VeterinarianResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('decline', 'Decline'), ('request_info', 'Request More Information')], max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from veterinarian')),
                ('response_time', models.IntegerField(help_text='Response time in seconds from notification to response')),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='consultations.consultationrequest')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_responses',
                'ordering': ['-responded_at'],
                'indexes': [models.Index(fields=['veterinarian', '-responded_at'], name='veterinaria_veterin_cd2a3d_idx'), models.Index(fields=['consultation_request', 'action'], name='veterinaria_consult_90be42_idx')],
                'unique_together': {('veterinarian', 'consultation_request')},
            },
        ),
        migrations.AddIndex(
            model_name='veterinarianpatient',
            index=models.Index(fields=['veterinarian', 'status'], name='veterinaria_veterin_44aecf_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinarianpatient',
            index=models.Index(fields=['cattle_owner'], name='veterinaria_cattle__19d382_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinarianpatient',
            index=models.Index(fields=['status', '-added_at'], name='veterinaria_status_ded1aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='veterinarianpatient',
            unique_together={('veterinarian', 'cattle')},
        ),
        migrations.AddIndex(
            model_name='veterinariannotificationrequest',
            index=models.Index(fields=['veterinarian', 'status'], name='veterinaria_veterin_b9b816_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinariannotificationrequest',
            index=models.Index(fields=['consultation_request'], name='veterinaria_consult_f6d1d3_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinariannotificationrequest',
            index=models.Index(fields=['distance_km'], name='veterinaria_distanc_1367e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='veterinariannotificationrequest',
            unique_together={('veterinarian', 'consultation_request')},
        ),
        migrations.AddIndex(
            model_name='veterinariandashboardstats',
            index=models.Index(fields=['veterinarian', '-last_updated'], name='veterinaria_veterin_d454e8_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['cattle_owner', '-reported_at'], name='symptom_rep_cattle__816e32_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['status', 'is_emergency'], name='symptom_rep_status_4264af_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['severity'], name='symptom_rep_severit_8c63b0_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnote',
            index=models.Index(fields=['patient', '-created_at'], name='patient_not_patient_e54e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientnote',
            index=models.Index(fields=['veterinarian', 'note_type'], name='patient_not_veterin_a30300_idx'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['patient', 'scheduled_date'], name='follow_up_s_patient_1939f5_idx'),
        ),
        migrations.AddIndex(
            model_name='followupschedule',
            index=models.Index(fields=['is_completed', 'scheduled_date'], name='follow_up_s_is_comp_da090d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status', 'priority'], name='consultatio_status_8fb004_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['cattle_owner', '-created_at'], name='consultatio_cattle__6953fb_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['assigned_veterinarian', 'status'], name='consultatio_assigne_ea528f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['expires_at'], name='consultatio_expires_bc1645_idx'),
        ),
    ]
