# Generated by Django 4.2.7 on 2025-12-26 17:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalDiseaseMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('disease_name', models.CharField(max_length=200)),
                ('case_count', models.IntegerField(default=0)),
                ('active_cases', models.IntegerField(default=0)),
                ('resolved_cases', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('first_reported', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('affected_cattle_count', models.IntegerField(default=0)),
                ('veterinarians_in_region', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'regional_disease_map',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['state', 'disease_name'], name='regional_di_state_91fb93_idx'), models.Index(fields=['risk_level', '-last_updated'], name='regional_di_risk_le_356531_idx'), models.Index(fields=['latitude', 'longitude'], name='regional_di_latitud_b3fd96_idx')],
                'unique_together': {('region_name', 'disease_name')},
            },
        ),
        migrations.CreateModel(
            name='VeterinarianPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('consultations_completed', models.IntegerField(default=0)),
                ('average_consultation_duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('consultation_success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_response_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('emergency_response_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('positive_feedback_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('diseases_diagnosed', models.IntegerField(default=0)),
                ('diagnostic_accuracy_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('regional_cases_handled', models.IntegerField(default=0)),
                ('outbreak_responses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'veterinarian_performance_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['veterinarian', '-date'], name='veterinaria_veterin_fd0379_idx'), models.Index(fields=['average_rating'], name='veterinaria_average_7e44b1_idx')],
                'unique_together': {('veterinarian', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HealthTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trend_type', models.CharField(choices=[('disease_occurrence', 'Disease Occurrence'), ('health_status', 'Health Status'), ('treatment_effectiveness', 'Treatment Effectiveness'), ('regional_outbreak', 'Regional Outbreak')], max_length=30)),
                ('date', models.DateField()),
                ('disease_name', models.CharField(blank=True, max_length=200)),
                ('location_data', models.JSONField(default=dict, help_text='Location information for regional trends')),
                ('case_count', models.IntegerField(default=0)),
                ('recovery_count', models.IntegerField(default=0)),
                ('mortality_count', models.IntegerField(default=0)),
                ('average_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('severity_distribution', models.JSONField(default=dict, help_text='Distribution of severity levels')),
                ('metadata', models.JSONField(default=dict, help_text='Additional trend metrics')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_trends',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'trend_type', '-date'], name='health_tren_user_id_b9b453_idx'), models.Index(fields=['disease_name', '-date'], name='health_tren_disease_a32b6f_idx'), models.Index(fields=['trend_type', '-date'], name='health_tren_trend_t_86ff3b_idx')],
                'unique_together': {('user', 'trend_type', 'disease_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stat_type', models.CharField(choices=[('cattle_owner', 'Cattle Owner Dashboard'), ('veterinarian', 'Veterinarian Dashboard'), ('system', 'System-wide Statistics')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_cattle', models.IntegerField(default=0)),
                ('healthy_cattle', models.IntegerField(default=0)),
                ('sick_cattle', models.IntegerField(default=0)),
                ('under_treatment_cattle', models.IntegerField(default=0)),
                ('total_health_assessments', models.IntegerField(default=0)),
                ('ai_predictions_made', models.IntegerField(default=0)),
                ('diseases_detected', models.IntegerField(default=0)),
                ('total_consultations', models.IntegerField(default=0)),
                ('completed_consultations', models.IntegerField(default=0)),
                ('cancelled_consultations', models.IntegerField(default=0)),
                ('emergency_consultations', models.IntegerField(default=0)),
                ('consultation_requests_received', models.IntegerField(default=0)),
                ('disease_alerts_received', models.IntegerField(default=0)),
                ('average_response_time_minutes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('regional_disease_cases', models.IntegerField(default=0)),
                ('regional_outbreak_alerts', models.IntegerField(default=0)),
                ('total_consultation_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'stat_type', '-date'], name='dashboard_s_user_id_c2df37_idx'), models.Index(fields=['stat_type', '-date'], name='dashboard_s_stat_ty_bf5988_idx')],
                'unique_together': {('user', 'stat_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CattleHealthMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('overall_health_score', models.DecimalField(decimal_places=2, help_text='Overall health score (0-100)', max_digits=5)),
                ('symptom_reports_count', models.IntegerField(default=0)),
                ('ai_assessments_count', models.IntegerField(default=0)),
                ('consultations_count', models.IntegerField(default=0)),
                ('treatments_received', models.IntegerField(default=0)),
                ('treatment_compliance_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('recovery_time_days', models.IntegerField(blank=True, null=True)),
                ('treatment_effectiveness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_factors', models.JSONField(default=list, help_text='List of identified risk factors')),
                ('predicted_health_issues', models.JSONField(default=list, help_text='AI-predicted potential health issues')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='cattle.cattle')),
            ],
            options={
                'db_table': 'cattle_health_metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['cattle', '-date'], name='cattle_heal_cattle__5557cd_idx'), models.Index(fields=['overall_health_score'], name='cattle_heal_overall_926e42_idx')],
                'unique_together': {('cattle', 'date')},
            },
        ),
    ]
