# Generated by Django 4.2.7 on 2025-12-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField(help_text='URL or path to the uploaded image')),
                ('predicted_class', models.CharField(help_text='Disease class predicted by Roboflow (e.g., "lumpy", "healthy")', max_length=100)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence score from 0 to 100', max_digits=5)),
                ('is_healthy', models.BooleanField(help_text='True if prediction indicates healthy cattle')),
                ('raw_response', models.JSONField(blank=True, help_text='Complete raw response from Roboflow API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(help_text='The cattle that was scanned', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='cattle.cattle')),
                ('user', models.ForeignKey(help_text='User who performed the scan', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'db_table': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_type', models.CharField(help_text='Type of disease detected', max_length=100)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Severity level of the disease', max_length=20)),
                ('recommendation', models.TextField(help_text='Recommended actions and treatment')),
                ('confirmed_by_vet', models.BooleanField(default=False, help_text='Whether a veterinarian has confirmed the diagnosis')),
                ('vet_notes', models.TextField(blank=True, help_text='Additional notes from veterinarian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(help_text='The affected cattle', on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to='cattle.cattle')),
                ('prediction', models.ForeignKey(blank=True, help_text='Associated prediction if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_records', to='dashboard.prediction')),
            ],
            options={
                'verbose_name': 'Disease Record',
                'verbose_name_plural': 'Disease Records',
                'db_table': 'disease_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='API endpoint that was called', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('disease', 'Disease Detected'), ('low_confidence', 'Low Confidence'), ('recognition_failure', 'Recognition Failure')], help_text='Type of alert', max_length=50)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], help_text='Severity level of the alert', max_length=20)),
                ('message', models.TextField(help_text='Alert message to display to user')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this alert')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='When user dismissed this alert', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, help_text='Associated prediction if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.prediction')),
                ('user', models.ForeignKey(help_text='User who should receive this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], help_text='Log level', max_length=20)),
                ('category', models.CharField(choices=[('failed_prediction', 'Failed Prediction'), ('invalid_image', 'Invalid Image'), ('low_confidence', 'Low Confidence'), ('api_error', 'API Error'), ('database_error', 'Database Error'), ('general', 'General')], help_text='Log category', max_length=50)),
                ('message', models.TextField(help_text='Log message')),
                ('details', models.JSONField(blank=True, help_text='Additional details as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, help_text='Associated prediction if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='dashboard.prediction')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='system_logs_level_245244_idx'), models.Index(fields=['category'], name='system_logs_categor_7ec442_idx'), models.Index(fields=['-created_at'], name='system_logs_created_9fcafe_idx'), models.Index(fields=['user'], name='system_logs_user_id_85bc8b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['-created_at'], name='predictions_created_794622_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['cow'], name='predictions_cow_id_4553ea_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user'], name='predictions_user_id_693109_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['is_healthy'], name='predictions_is_heal_3345e4_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['predicted_class'], name='predictions_predict_5c791b_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaserecord',
            index=models.Index(fields=['cow'], name='disease_rec_cow_id_5fcf01_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaserecord',
            index=models.Index(fields=['-created_at'], name='disease_rec_created_5ddba1_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaserecord',
            index=models.Index(fields=['disease_type'], name='disease_rec_disease_fc5e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaserecord',
            index=models.Index(fields=['severity'], name='disease_rec_severit_c3d0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaserecord',
            index=models.Index(fields=['confirmed_by_vet'], name='disease_rec_confirm_f24c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['-created_at'], name='api_usage_l_created_f6e847_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['endpoint'], name='api_usage_l_endpoin_133785_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['status_code'], name='api_usage_l_status__582b53_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusagelog',
            index=models.Index(fields=['user'], name='api_usage_l_user_id_2a4c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user'], name='alerts_user_id_869dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read'], name='alerts_is_read_fc9dae_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alerts_created_6327ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='alerts_alert_t_eda531_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='alerts_severit_362484_idx'),
        ),
    ]
