# Generated by Django 4.2.7 on 2026-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City ID from location data', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, help_text='PIN/ZIP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State code (e.g., KA, MH)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state'], name='users_state_bd654f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['city'], name='users_city_9c6023_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['state', 'city'], name='users_state_99d491_idx'),
        ),
    ]
