# Generated by Django 4.2.7 on 2025-12-01 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(help_text='Detailed description of the disease')),
                ('common_symptoms', models.JSONField(default=list, help_text='List of common symptoms')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('traditional_treatments', models.JSONField(default=list, help_text='List of traditional/herbal treatments')),
                ('allopathic_treatments', models.JSONField(default=list, help_text='List of allopathic/modern treatments')),
                ('prevention_measures', models.TextField(blank=True, null=True)),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this disease is active in the detection system')),
                ('detection_confidence_threshold', models.FloatField(default=0.6, help_text='Minimum confidence score (0-1) for AI to predict this disease')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diseases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dataset_file', models.FileField(help_text='ZIP file containing training images', upload_to='training_datasets/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_images', models.IntegerField(default=0)),
                ('processed_images', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the dataset')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_datasets', to='health.disease')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Dataset',
                'verbose_name_plural': 'Training Datasets',
                'db_table': 'training_datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField(help_text='Detailed description of observable symptoms', validators=[django.core.validators.MinLengthValidator(10, message='Symptom description must be at least 10 characters')])),
                ('observed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_entries', to='cattle.cattle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom Entry',
                'verbose_name_plural': 'Symptom Entries',
                'db_table': 'symptom_entries',
                'ordering': ['-observed_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Health image (JPEG or PNG, max 10MB)', upload_to='health_images/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('lesion', 'Lesion'), ('wound', 'Wound'), ('discharge', 'Discharge'), ('general', 'General')], default='general', max_length=50)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (size, format, dimensions)')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_images', to='cattle.cattle')),
                ('symptom_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health.symptomentry')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Image',
                'verbose_name_plural': 'Health Images',
                'db_table': 'health_images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_file', models.FileField(help_text='Trained model file (.h5, .pkl, etc.)', upload_to='ai_models/')),
                ('training_dataset_count', models.IntegerField(default=0)),
                ('training_image_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('deployed', 'Deployed'), ('archived', 'Archived'), ('failed', 'Failed')], default='training', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this model is currently being used for predictions')),
                ('training_config', models.JSONField(blank=True, default=dict, help_text='Training configuration and hyperparameters')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_models', to=settings.AUTH_USER_MODEL)),
                ('diseases', models.ManyToManyField(help_text='Diseases this model can detect', related_name='ai_models', to='health.disease')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Training image for disease detection', upload_to='training_images/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('image_hash', models.CharField(help_text='SHA256 hash to prevent duplicates', max_length=64, unique=True)),
                ('labels', models.JSONField(default=list, help_text='Additional labels or tags for this image')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Bounding boxes or other annotations')),
                ('is_validated', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(blank=True, help_text='Image quality score (0-1)', null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='health.trainingdataset')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_images', to='health.disease')),
            ],
            options={
                'verbose_name': 'Training Image',
                'verbose_name_plural': 'Training Images',
                'db_table': 'training_images',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['disease', '-uploaded_at'], name='training_im_disease_d4207a_idx'), models.Index(fields=['image_hash'], name='training_im_image_h_d5c7c7_idx'), models.Index(fields=['is_validated'], name='training_im_is_vali_3ad9b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingdataset',
            index=models.Index(fields=['disease', '-uploaded_at'], name='training_da_disease_087e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingdataset',
            index=models.Index(fields=['status'], name='training_da_status_3809da_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomentry',
            index=models.Index(fields=['cattle', '-observed_date'], name='symptom_ent_cattle__28457a_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomentry',
            index=models.Index(fields=['severity'], name='symptom_ent_severit_42b964_idx'),
        ),
        migrations.AddIndex(
            model_name='healthimage',
            index=models.Index(fields=['cattle', '-upload_date'], name='health_imag_cattle__23b5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='healthimage',
            index=models.Index(fields=['symptom_entry'], name='health_imag_symptom_02290a_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['name'], name='diseases_name_82f10d_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['is_active'], name='diseases_is_acti_a996a2_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['version'], name='ai_models_version_b16afc_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['status'], name='ai_models_status_4c9e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['is_active'], name='ai_models_is_acti_b1b072_idx'),
        ),
    ]
