# Generated by Django 4.2.7 on 2025-12-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_type', models.CharField(choices=[('immediate', 'Immediate Action'), ('daily', 'Daily Treatment'), ('monitoring', 'Monitoring'), ('followup', 'Follow-up')], max_length=20)),
                ('instructions', models.TextField()),
                ('timing', models.CharField(help_text='When to perform this step (e.g., "Day 1", "Every 12 hours")', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='How long to continue this step', max_length=100, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions that must be met for this step')),
            ],
            options={
                'db_table': 'protocol_steps',
                'ordering': ['protocol', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the treatment')),
                ('ingredients', models.JSONField(default=list, help_text='List of active ingredients or components')),
                ('dosage', models.TextField(help_text='Dosage instructions')),
                ('administration_method', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection', 'Injection'), ('intravenous', 'Intravenous'), ('intramuscular', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('inhalation', 'Inhalation'), ('feed_additive', 'Feed Additive'), ('water_additive', 'Water Additive')], default='oral', max_length=20)),
                ('frequency', models.CharField(help_text='How often to administer (e.g., "twice daily", "every 8 hours")', max_length=100)),
                ('duration', models.CharField(help_text='Treatment duration (e.g., "5-7 days", "until symptoms resolve")', max_length=100)),
                ('preparation_method', models.TextField(blank=True, help_text='How to prepare the treatment (for traditional remedies)', null=True)),
                ('precautions', models.JSONField(default=list, help_text='List of precautions and warnings')),
                ('side_effects', models.JSONField(default=list, help_text='List of potential side effects')),
                ('contraindications', models.JSONField(default=list, help_text='Conditions where this treatment should not be used')),
                ('effectiveness', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='moderate', max_length=20)),
                ('evidence_level', models.CharField(blank=True, help_text='Level of scientific evidence (e.g., "Clinical trials", "Traditional use")', max_length=100, null=True)),
                ('availability', models.CharField(blank=True, help_text='Where to obtain this treatment', max_length=200, null=True)),
                ('estimated_cost', models.CharField(blank=True, help_text='Estimated cost range', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=False, help_text='Whether this treatment requires veterinary prescription')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatments',
                'db_table': 'treatments',
                'ordering': ['category__category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('traditional', 'Traditional/Herbal'), ('allopathic', 'Allopathic/Modern'), ('supportive', 'Supportive Care'), ('preventive', 'Preventive')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Treatment Category',
                'verbose_name_plural': 'Treatment Categories',
                'db_table': 'treatment_categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('protocol_type', models.CharField(choices=[('standard', 'Standard Protocol'), ('emergency', 'Emergency Protocol'), ('chronic', 'Chronic Management'), ('preventive', 'Preventive Protocol')], max_length=20)),
                ('description', models.TextField()),
                ('severity_range', models.JSONField(default=list, help_text='Severity levels this protocol applies to')),
                ('age_range', models.JSONField(blank=True, default=dict, help_text='Age range this protocol applies to')),
                ('total_duration', models.CharField(help_text='Total expected duration of protocol', max_length=100)),
                ('expected_outcomes', models.JSONField(default=list, help_text='Expected outcomes and timeline')),
                ('success_indicators', models.JSONField(default=list, help_text='Signs that treatment is working')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_veterinary_supervision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protocols', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='health.disease')),
                ('treatments', models.ManyToManyField(related_name='protocols', through='health.ProtocolStep', to='health.treatment')),
            ],
            options={
                'verbose_name': 'Treatment Protocol',
                'verbose_name_plural': 'Treatment Protocols',
                'db_table': 'treatment_protocols',
                'ordering': ['disease', 'protocol_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='treatment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='health.treatmentcategory'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='diseases',
            field=models.ManyToManyField(help_text='Diseases this treatment is effective for', related_name='treatments', to='health.disease'),
        ),
        migrations.AddField(
            model_name='protocolstep',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='health.treatmentprotocol'),
        ),
        migrations.AddField(
            model_name='protocolstep',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.treatment'),
        ),
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_strength', models.CharField(choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong'), ('very_strong', 'Very Strong')], default='moderate', max_length=20)),
                ('priority_order', models.IntegerField(default=1, help_text='Priority order for this treatment (1 = highest priority)')),
                ('severity_specific', models.JSONField(blank=True, default=dict, help_text='Adjustments based on disease severity')),
                ('age_specific', models.JSONField(blank=True, default=dict, help_text='Age-specific dosage or precautions')),
                ('breed_specific', models.JSONField(blank=True, default=dict, help_text='Breed-specific considerations')),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this disease-treatment combination', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_recommendations', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_recommendations', to='health.disease')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='health.treatment')),
            ],
            options={
                'verbose_name': 'Treatment Recommendation',
                'verbose_name_plural': 'Treatment Recommendations',
                'db_table': 'treatment_recommendations',
                'ordering': ['disease', 'priority_order'],
                'indexes': [models.Index(fields=['disease', 'priority_order'], name='treatment_r_disease_1fefd1_idx'), models.Index(fields=['recommendation_strength'], name='treatment_r_recomme_e2768d_idx')],
                'unique_together': {('disease', 'treatment')},
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['name'], name='treatments_name_145518_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['category', 'effectiveness'], name='treatments_categor_a36357_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['is_active'], name='treatments_is_acti_b900f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolstep',
            unique_together={('protocol', 'step_number')},
        ),
    ]
